[web]
  title = "Surface RedwoodTemplate"
  port = 8910
  apiUrl = "${REDWOOD_API_URL:/.redwood/functions}"
  includeEnvironmentVariables = ["SUPABASE_URL","SUPABASE_KEY"]
[api]
  port = 8911
[browser]
  open = true
